# Generated by Django 2.1.15 on 2020-03-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(db_column='UserId', max_length=50)),
                ('address', models.EmailField(db_column='Address', max_length=50)),
                ('role', models.CharField(choices=[('R', 'requestor'), ('A', 'approver')], db_column='Role', default='R', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ordernumber', models.BigIntegerField(db_column='OrderNumber', primary_key=True, serialize=False)),
                ('requestor', models.CharField(db_column='Requestor', max_length=50)),
                ('lastmodified', models.DateTimeField(auto_now=True, db_column='LastModified', null=True)),
                ('email', models.ForeignKey(db_column='Address', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Email')),
            ],
        ),
    ]
