# Generated by Django 2.1.15 on 2020-04-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200416_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': [('can mark book instance', 'mark_bookinstance')]},
        ),
    ]
